### ISSUE TITLE
how to document what terms are used in each framework

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/data_dictionary#13]
Should we create an entry for each framework of interest if they use a term other than the term of choice? For example, if FLR uses spawning stock biomass instead of spawning biomass in their documentation and figures we could have an entry like the following
```
Spawning Biomass: ...
Alternatives: spawning stock biomass
FLR: spawning stock biomass
```
or do we list who uses the alternatives in parentheses after, though I have been using this latter notation for units
```
Alternatives: spawning stock biomass (FLR)
```
Obviously, other ideas are welcome.

**Comment by chantelwetzel-noaa** [comment]
If we want to have the functionality of search through the glossary and linking the term we are recommending versus a specific software, the first option might be best.  However, if that is not necessary, the second option would likely simpler to maintain since terms from software packages could just be added to the list, rather than having to add a line item for that package across all terms.  Does that make sense?

**Comment by kellijohnson-NOAA** [comment]
I was hoping that we would not have to have every category for each entry but the current way it is read in requires all categories be present.

**Comment by kellijohnson-NOAA** [comment]
On 2022-03-04 we decided to **NOT** document in the top20.txt file how the term is used in each framework. ICES references were thus removed. Instead, maintainers of software packages will be able to document this for their own package if they want to using future R functionality (see #15).
